version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5

  features:
    build: ./features
    depends_on:
      - rabbitmq
    restart: on-failure

  model:
    build: ./model
    depends_on:
      - rabbitmq
      - features
    restart: on-failure

  metric:
    build: ./metric
    volumes:
      - ./logs:/logs
    depends_on:
      - rabbitmq
      - model
    restart: on-failure

  plot:
    build: ./plot
    volumes:
      - ./logs:/logs
    depends_on:
      - metric    
    restart: on-failure